/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graph;

import FillShape.EllipsePanel;
import FillShape.RectanglePanel;
import Line.LinePanel;
import java.awt.Point;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JColorChooser;

/**
 *
 * @author Administrator
 */
public class Paint extends javax.swing.JFrame {
    Point p1 = null, p2 = null;
    Color color = Color.RED;
    LinePanel linePanel = null;
    RectanglePanel recPanel = null;
    EllipsePanel ellipsePanel = null;
    
    /**
     * Creates new form Paint
     */
    public Paint() {
        initComponents();
        this.setSize(500, 500);
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbDraw); bg.add(rbFill);
        rbDraw.setSelected(true);
        rbFill.setEnabled(false); 
        // add line panel
        linePanel = new LinePanel();
        pTabbed.add(linePanel);
        pTabbed.setTitleAt(0, "Lines");
        // add rectangle panel
        recPanel = new RectanglePanel();
        pTabbed.add(recPanel);
        pTabbed.setTitleAt(1, "Rectangles");
        // add ellipse panel
        ellipsePanel = new EllipsePanel();
        pTabbed.add(ellipsePanel);
        pTabbed.setTitleAt(2, "Ellipses");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnColor = new javax.swing.JButton();
        rbDraw = new javax.swing.JRadioButton();
        rbFill = new javax.swing.JRadioButton();
        pTabbed = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnColor.setText("Select Color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        jPanel1.add(btnColor);

        rbDraw.setText("Draw Only");
        rbDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDrawActionPerformed(evt);
            }
        });
        jPanel1.add(rbDraw);

        rbFill.setText("Draw and Fill");
        rbFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFillActionPerformed(evt);
            }
        });
        jPanel1.add(rbFill);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pTabbed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTabbedMouseClicked(evt);
            }
        });
        getContentPane().add(pTabbed, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        color = JColorChooser.showDialog(this, "Choose a color", Color.RED);
        linePanel.setColor(color);
        recPanel.setColor(color);
        ellipsePanel.setColor(color);                    
    }//GEN-LAST:event_btnColorActionPerformed

    private void pTabbedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTabbedMouseClicked
        int index = pTabbed.getSelectedIndex();
        switch(index){
            case 0:
                rbDraw.setSelected(true);
                rbFill.setEnabled(false);
                recPanel.setFill(false);
                ellipsePanel.setFill(false);                
                break;
            case 1:
                rbFill.setEnabled(true);                
                break;
            case 2:
                rbFill.setEnabled(true);
                break;                
        }
    }//GEN-LAST:event_pTabbedMouseClicked

    private void rbDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDrawActionPerformed
        recPanel.setFill(false);
        ellipsePanel.setFill(false);
    }//GEN-LAST:event_rbDrawActionPerformed

    private void rbFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFillActionPerformed
        recPanel.setFill(true);
        ellipsePanel.setFill(true);
    }//GEN-LAST:event_rbFillActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane pTabbed;
    private javax.swing.JRadioButton rbDraw;
    private javax.swing.JRadioButton rbFill;
    // End of variables declaration//GEN-END:variables
}
