/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FillShape;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.LinkedList;

/**
 *
 * @author Administrator
 */
public class EllipsePanel extends javax.swing.JPanel {

    LinkedList<Component> ellipseList = new LinkedList<>();
    Point startPnt = null, endPnt = null;
    Graphics g = null;
    Color color = Color.RED;
    boolean fill = false;

    public EllipsePanel() {
        initComponents();
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public void setFill(boolean fill) {
        this.fill = fill;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);        
        for (Component ellipse : ellipseList) {
            Point p1 = ellipse.startPoint;
            Point p2 = ellipse.endPoint;
            g.setColor(ellipse.color);
            if (!ellipse.fill) {
                g.drawOval(ellipse.left, ellipse.top, ellipse.width, ellipse.height);
            } else {
                g.fillOval(ellipse.left, ellipse.top, ellipse.width, ellipse.height);
            }
        }
        if (startPnt == null && endPnt == null) {
            return;
        }
        g.setColor(color);
        Component tmpElp = new Component(startPnt, endPnt);
        if (fill) {
            g.fillOval(tmpElp.left, tmpElp.top, tmpElp.width, tmpElp.height);
        } else {
            g.drawOval(tmpElp.left, tmpElp.top, tmpElp.width, tmpElp.height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        startPnt = evt.getPoint();
        g = this.getGraphics();
        g.setColor(color);
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        endPnt = evt.getPoint();
        if (startPnt == null || endPnt == null) {
            return;
        }
        Component elp = new Component(startPnt, endPnt, fill, color);
        ellipseList.add(elp);
        if (fill) {
            g.fillOval(elp.left, elp.top, elp.width, elp.height);
        } else {
            g.drawOval(elp.left, elp.top, elp.width, elp.height);
        }
        startPnt = endPnt = null;
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        endPnt = evt.getPoint();
        repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
