/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FillShape;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.LinkedList;

/**
 *
 * @author Administrator
 */
public class RectanglePanel extends javax.swing.JPanel {
    LinkedList<Component> recList = new LinkedList<>();
    Point startPnt = null, endPnt = null;
    Graphics g = null;
    Color color = Color.RED;
    boolean fill = false;

    public RectanglePanel() {
        initComponents();
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public void setFill(boolean fill) {
        this.fill = fill;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);        
        for (Component rec : recList) {
            Point p1 = rec.startPoint;
            Point p2 = rec.endPoint;
            g.setColor(rec.color);
            if (!rec.fill) {
                g.drawRect(rec.left, rec.top, rec.width, rec.height);
            } else {
                g.fillRect(rec.left, rec.top, rec.width, rec.height);
            }
        }
        if(startPnt == null && endPnt == null)
            return;
        g.setColor(color);
        Component tmpRec = new Component(startPnt, endPnt);
        if (fill) {
            g.fillRect(tmpRec.left, tmpRec.top, tmpRec.width, tmpRec.height);
        } else {
            g.drawRect(tmpRec.left, tmpRec.top, tmpRec.width, tmpRec.height);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        startPnt = evt.getPoint();
        g = this.getGraphics();
        g.setColor(color);        
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        endPnt = evt.getPoint();
        if (startPnt == null || endPnt == null) {
            return;
        }
        Component rec = new Component(startPnt, endPnt, fill, color);
        recList.add(rec);
        if (fill) {
            g.fillRect(rec.left, rec.top, rec.width, rec.height);
        } else {
            g.drawRect(rec.left, rec.top, rec.width, rec.height);
        }
        startPnt = endPnt = null;
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        endPnt = evt.getPoint();
        repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
